name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:      
    
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.ACTION_USER }}
        password: ${{ secrets.ACTION_TOKEN }}

    - name: Pull SSL certs from Github secrets    
      run: echo "${{ secrets.PROD_ENV }}" | base64 --decode > ./src/environments/environment.ts

    - name: Compile project
      run: npm install; npm run build
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ianpolettilucero/nkc-front:latest

    - name: Publish to Github Registry
      run: docker push ghcr.io/ianpolettilucero/nkc-front:latest
